# Generated by Django 5.1.1 on 2025-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_conversation_message_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='accent_color',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')], default='pink', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish')], default='en-US', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', max_length=20),
        ),
    ]
